version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - APOS_MONGODB_URI=mongodb://mongo:27017/apostrophecms-site
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: